# Generated by Django 5.2.14 on 2026-05-21 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('FIELD_ESCAPE', 'FIELD_ESCAPE'), ('REFUSED_CONTROL', 'REFUSED_CONTROL'), ('SUSPICIOUS_BEHAVIOR', 'SUSPICIOUS_BEHAVIOR'), ('WANTED_VEHICLE', 'WANTED_VEHICLE'), ('STOLEN_PLATE', 'STOLEN_PLATE'), ('JUDICIAL_ALERT', 'JUDICIAL_ALERT')], max_length=40)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
