# Generated by Django 5.2.14 on 2026-06-23 16:06

import apps.alerts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(storage=apps.alerts.models.PrivateAlertEvidenceStorage(), upload_to=apps.alerts.models.alert_evidence_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='alerts.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
