# Generated by Django 5.2.14 on 2026-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevidence',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
