# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_person_birth_date_and_more'),
        ('alerts', '0006_alert_category'),
        ('vehicles', '0003_vehicle_registration_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='alert',
            name='document_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], db_index=True, default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Résolue'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='subject_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounts.person'),
        ),
        migrations.AddField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('FIELD_ESCAPE', 'Fuite lors du contrôle'), ('REFUSED_CONTROL', 'Refus de contrôle'), ('SUSPICIOUS_BEHAVIOR', 'Comportement suspect'), ('WANTED_VEHICLE', 'Véhicule volé ou recherché'), ('STOLEN_PLATE', 'Plaque volée'), ('JUDICIAL_ALERT', 'Alerte judiciaire'), ('DOCUMENT_EXPIRY_WARNING', "Document proche de l'expiration")], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuelle'), ('SYSTEM', 'Système')], db_index=True, default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='subject_nif',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='checksum_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='evidence_type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Vidéo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category', 'status', 'created_at'], name='alert_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity', 'created_at'], name='alert_status_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['vehicle', 'alert_type', 'status'], name='alert_vehicle_type_idx'),
        ),
    ]
