# Generated by Django 5.2.16 on 2026-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0007_alter_alert_options_alert_document_expires_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("FIELD_ESCAPE", "Fuite lors du controle"),
                    ("REFUSED_CONTROL", "Refus de controle"),
                    ("SUSPICIOUS_BEHAVIOR", "Comportement suspect"),
                    ("KIDNAPPING", "Enlevement"),
                    ("WANTED_VEHICLE", "Vehicule vole ou recherche"),
                    ("STOLEN_PLATE", "Plaque volee"),
                    ("JUDICIAL_ALERT", "Alerte judiciaire"),
                    ("DOCUMENT_EXPIRY_WARNING", "Document proche de l'expiration"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manuelle"), ("SYSTEM", "Systeme")],
                db_index=True,
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RESOLVED", "Resolue"),
                    ("CANCELLED", "Annulee"),
                    ("EXPIRED", "Expiree"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alertevidence",
            name="evidence_type",
            field=models.CharField(
                choices=[("AUDIO", "Audio"), ("VIDEO", "Video")],
                max_length=10,
            ),
        ),
    ]