# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_agentprofile_user_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Facultative lorsque cette information n'est pas encore disponible, notamment pour un propriétaire.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Peut rester vide uniquement pour un superutilisateur technique ou temporairement durant une migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.person'),
        ),
    ]
