# Generated by Django 5.2.14 on 2026-07-22 20:00

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_person_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.SmartRouteUserManager()),
            ],
        ),
    ]
