# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_limit_status_choices_to_valid_expired'),
        ('vehicles', '0003_vehicle_registration_valid_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'ordering': ['-valid_until', '-id'], 'verbose_name': "Police d'assurance", 'verbose_name_plural': "Polices d'assurance"},
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valide'), ('EXPIRED', 'Expirée'), ('SUSPENDED', 'Suspendue'), ('CANCELLED', 'Annulée')], db_index=True, default='VALID', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='valid_until',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['vehicle', 'status'], name='insurance_vehicle_status_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_policy_number_idx'),
        ),
    ]
