# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role_snapshot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='app_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('STATUS_CHANGE', 'Changement de statut'), ('CANCEL', 'Annulation'), ('CLOSE', 'Clôture'), ('ADD_PROOF', 'Ajout de preuve'), ('ADD_EVIDENCE', 'Ajout de preuve de délit'), ('ADD_ACTION', "Ajout d'action"), ('SUBMIT_REVIEW', 'Soumission pour examen'), ('CONFIRM', 'Confirmation'), ('REJECT', 'Rejet'), ('REFER', 'Transmission'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('ACCOUNT_SUSPEND', 'Suspension du compte'), ('ACCOUNT_REACTIVATE', 'Réactivation du compte'), ('DEVICE_REGISTER', "Enregistrement d'appareil"), ('DEVICE_REVOKE', "Révocation d'appareil"), ('LICENSE_RETAIN', 'Rétention de permis'), ('LICENSE_RELEASE', 'Restitution de permis'), ('OTHER', 'Autre')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_object_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'action', 'created_at'], name='audit_actor_action_idx'),
        ),
    ]
