# Generated by Django 5.2.14 on 2026-07-22 19:37

import apps.media_storage.services
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('vehicles', '0003_vehicle_registration_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Pièce jointe véhicule', 'verbose_name_plural': 'Pièces jointes véhicule'},
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('VEHICLE_PHOTO', 'Photo du véhicule'), ('REGISTRATION_COPY', 'Copie de carte grise'), ('INSURANCE_COPY', "Copie d'assurance"), ('INSPECTION_COPY', 'Copie de contrôle technique'), ('SUPPORTING_DOCUMENT', 'Pièce justificative'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=40),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.media_storage.services.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vehicle', 'document_type'], name='doc_vehicle_type_idx'),
        ),
    ]
