# Generated by Django 5.2.14 on 2026-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ('display_order', 'code')},
        ),
        migrations.AddField(
            model_name='infraction',
            name='article',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='infraction',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='infraction',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='infraction',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='infraction',
            name='penalty_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='label',
            field=models.CharField(max_length=220),
        ),
    ]
