# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0002_alter_infraction_options_infraction_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ('display_order', 'code'), 'verbose_name': 'Infraction', 'verbose_name_plural': 'Infractions'},
        ),
        migrations.AddField(
            model_name='infraction',
            name='amount_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='infraction',
            name='authority_review_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infraction',
            name='currency',
            field=models.CharField(default='HTG', max_length=3),
        ),
        migrations.AddField(
            model_name='infraction',
            name='legal_classification',
            field=models.CharField(choices=[('CONTRAVENTION', 'Contravention'), ('POSSIBLE_OFFENSE', 'Délit potentiel à valider'), ('OFFENSE', 'Délit confirmé'), ('TO_VALIDATE', 'Qualification à valider')], db_index=True, default='CONTRAVENTION', max_length=24),
        ),
        migrations.AddField(
            model_name='infraction',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='infraction',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='infraction',
            name='official_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infraction',
            name='penalty_type',
            field=models.CharField(choices=[('FIXED', 'Montant fixe'), ('RANGE', 'Intervalle'), ('MULTIPLE', 'Plusieurs montants possibles'), ('TEXT_ONLY', 'Sanction textuelle'), ('NONE', 'Aucun montant renseigné')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='infraction',
            name='requires_authority_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='article',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='category',
            field=models.CharField(choices=[('CIRCULATION', 'Circulation'), ('PARKING', 'Arrêt et stationnement'), ('DOCUMENTS', 'Documents'), ('REGISTRATION', 'Immatriculation'), ('EQUIPMENT', 'Équipement du véhicule'), ('DRIVER_BEHAVIOR', 'Comportement du conducteur'), ('PUBLIC_TRANSPORT', 'Transport public'), ('ACCIDENT', 'Accident'), ('ROAD_INFRASTRUCTURE', 'Voie et signalisation'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=40),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='penalty_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='infraction',
            index=models.Index(fields=['active', 'category', 'display_order'], name='inf_active_category_idx'),
        ),
        migrations.AddIndex(
            model_name='infraction',
            index=models.Index(fields=['legal_classification', 'requires_authority_review'], name='inf_legal_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='infraction',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='infraction_number_gt_zero'),
        ),
    ]
