# Generated by Django 5.2.14 on 2026-05-21 16:48

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infractions', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('driver_license', models.CharField(max_length=80)),
                ('plate_number_snapshot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_SYNC', 'PENDING_SYNC'), ('ISSUED', 'ISSUED'), ('VALIDATED', 'VALIDATED'), ('CANCELLED', 'CANCELLED'), ('PAID', 'PAID')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('barcode_value', models.CharField(blank=True, max_length=64)),
                ('barcode_image', models.ImageField(blank=True, upload_to='barcodes/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketInfraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infractions.infraction')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_infractions', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.tickets.models.proof_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
