# Generated by Django 5.2.14 on 2026-07-01 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproof',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticketproof',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketproof',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
