# Generated by Django 5.2.14 on 2026-07-22 19:37

import apps.media_storage.services
import apps.tickets.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0003_alter_infraction_options_infraction_amount_options_and_more'),
        ('tickets', '0008_ticket_verbalization_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='driver_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pricing_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Non demandé'), ('PENDING', 'Demande en cours'), ('AVAILABLE', 'Disponible'), ('FAILED', 'Échec')], db_index=True, default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'En cours'), ('CLOSED', 'Clôturé'), ('CANCELLED', 'Annulé')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SYNCED', 'Synchronisé'), ('FAILED', 'Échec')], db_index=True, default='SYNCED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticketinfraction',
            name='infraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verbalization_links', to='infractions.infraction'),
        ),
        migrations.AlterField(
            model_name='ticketinfraction',
            name='verbalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='tickets.ticketverbalization'),
        ),
        migrations.AlterField(
            model_name='ticketproof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticketproof',
            name='evidence_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio')], default='PHOTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketproof',
            name='file',
            field=models.FileField(storage=apps.tickets.models.PrivateTicketProofStorage(), upload_to=apps.media_storage.services.ticket_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='ticketproof',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='ticketproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticketverbalization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Annulée')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
