# Generated by Django 5.2.14 on 2026-06-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_license_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
