# Generated by Django 5.2.14 on 2026-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_person_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
