# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_uuid', models.UUIDField(db_index=True, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('OTHER', 'Autre')], default='ANDROID', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_sync_devices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('request_uuid', models.UUIDField(db_index=True, unique=True)),
                ('direction', models.CharField(choices=[('PUSH', 'Envoi'), ('PULL', 'Réception')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('SUCCESS', 'Réussi'), ('PARTIAL_SUCCESS', 'Partiellement réussi'), ('FAILED', 'Échec')], db_index=True, default='PENDING', max_length=20)),
                ('cursor', models.DateTimeField(blank=True, null=True)),
                ('next_cursor', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_sessions', to='sync.syncdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SyncItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entity_type', models.CharField(choices=[('TICKET', 'Procès-verbal'), ('VERBALIZATION', 'Verbalisation'), ('TICKET_PROOF', 'Preuve de verbalisation'), ('DELIT_CASE', 'Dossier de délit'), ('DELIT_EVIDENCE', 'Preuve de délit')], max_length=30)),
                ('operation', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('UPSERT', 'Création ou mise à jour')], max_length=10)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('server_id', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échec'), ('CONFLICT', 'Conflit'), ('DUPLICATE', 'Doublon')], db_index=True, default='PENDING', max_length=20)),
                ('base_version', models.PositiveIntegerField(blank=True, null=True)),
                ('server_version', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync.syncsession')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='SyncLog',
        ),
        migrations.AddConstraint(
            model_name='syncdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_uuid'), name='unique_sync_device_per_user'),
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['user', 'device', 'direction', 'status'], name='sync_session_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='syncitemlog',
            index=models.Index(fields=['entity_type', 'client_uuid', 'status'], name='sync_item_entity_uuid_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncitemlog',
            constraint=models.UniqueConstraint(fields=('session', 'entity_type', 'client_uuid', 'operation'), name='unique_item_per_sync_session'),
        ),
    ]
