"""Official DCPR infraction catalog used to seed the backend.
Source: SmartRoute project DCPR list previously used by the mobile UI.
The backend is now the runtime source of truth; keep this file in sync with official updates.
"""

OFFICIAL_INFRACTIONS = [
    {
        'number': 1,
        'code': 'I001',
        'label': "Doubler une file de véhicules en cas d'embouteillage",
        'article': 'Art. 97',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 1,
        'active': True,
    },
    {
        'number': 2,
        'code': 'I002',
        'label': 'Arrêt ou stationnement en double file',
        'article': 'Art. 88 à 91',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 2,
        'active': True,
    },
    {
        'number': 3,
        'code': 'I003',
        'label': 'Obstruer la circulation (véhicule)/Faire demi-tour',
        'article': 'Art. 87',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 3,
        'active': True,
    },
    {
        'number': 4,
        'code': 'I004',
        'label': "Manquer d'égard à un agent dans l'exercice de ses fonctions",
        'article': 'Art. 43',
        'amount': '250',
        'penalty_text': '250',
        'category': '',
        'display_order': 4,
        'active': True,
    },
    {
        'number': 5,
        'code': 'I005',
        'label': 'Refuser de présenter son permis',
        'article': 'Art. 43',
        'amount': '250',
        'penalty_text': '250',
        'category': '',
        'display_order': 5,
        'active': True,
    },
    {
        'number': 6,
        'code': 'I006',
        'label': "Circuler sans permis ou sans carte d'enregistrement / assurance périmée",
        'article': 'Art. 40',
        'amount': '2000',
        'penalty_text': '2000',
        'category': '',
        'display_order': 6,
        'active': True,
    },
    {
        'number': 7,
        'code': 'I007',
        'label': "Circuler sans fiche d'inspection / avec une fiche périmée ou détériorée",
        'article': 'Art. 136.a',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 7,
        'active': True,
    },
    {
        'number': 8,
        'code': 'I008',
        'label': 'Ne pas remplacer la fiche égarée. Ne pas signaler la perte au SCV.',
        'article': 'Art. 136.b',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 8,
        'active': True,
    },
    {
        'number': 9,
        'code': 'I009',
        'label': 'Circuler sans "Feu stop" - sans "Feu rouge" - sans "feux de pavillon" (camion) - sans "feu de gabari" - sans "feux d\'eclairage".',
        'article': 'Art. 148',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 9,
        'active': True,
    },
    {
        'number': 10,
        'code': 'I010',
        'label': 'Circuler sans plaque ou avec une plaque non conforme',
        'article': 'Art. 34',
        'amount': '12500',
        'penalty_text': '12500',
        'category': '',
        'display_order': 10,
        'active': True,
    },
    {
        'number': 11,
        'code': 'I011',
        'label': 'Stationnement interdit',
        'article': 'Art. 88 à 91',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 11,
        'active': True,
    },
    {
        'number': 12,
        'code': 'I012',
        'label': 'Circuler avec une seule lumière',
        'article': 'Art. 148',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 12,
        'active': True,
    },
    {
        'number': 13,
        'code': 'I013',
        'label': 'Circuler avec une plaque abîmée et illisible',
        'article': 'Art. 39',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 13,
        'active': True,
    },
    {
        'number': 14,
        'code': 'I014',
        'label': 'Circuler sans lumière',
        'article': 'Art. 148',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 14,
        'active': True,
    },
    {
        'number': 15,
        'code': 'I015',
        'label': 'Circuler à gauche',
        'article': 'Art. 77',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 15,
        'active': True,
    },
    {
        'number': 16,
        'code': 'I016',
        'label': 'Dépasser à droite',
        'article': 'Art. 80',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 16,
        'active': True,
    },
    {
        'number': 17,
        'code': 'I017',
        'label': 'Circuler avec les feux de route dans les villes et agglomérations',
        'article': 'Art. 149',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 17,
        'active': True,
    },
    {
        'number': 18,
        'code': 'I018',
        'label': 'Circuler sans réflecteurs',
        'article': 'Art. 148.8',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 18,
        'active': True,
    },
    {
        'number': 19,
        'code': 'I019',
        'label': 'Excès de vitesse',
        'article': 'Art. 82',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 19,
        'active': True,
    },
    {
        'number': 20,
        'code': 'I020',
        'label': 'Franchir un feu rouge',
        'article': 'Art. 104',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 20,
        'active': True,
    },
    {
        'number': 21,
        'code': 'I021',
        'label': 'Prendre la fuite après un accident',
        'article': 'Art. 142-143',
        'amount': None,
        'penalty_text': '5000 - 10000',
        'category': '',
        'display_order': 21,
        'active': True,
    },
    {
        'number': 22,
        'code': 'I022',
        'label': 'Arrêt ou stationnement dans un virage',
        'article': 'Art. 89',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 22,
        'active': True,
    },
    {
        'number': 23,
        'code': 'I023',
        'label': 'Arrêt ou stationnement dans un carrefour',
        'article': 'Art. 90-91',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 23,
        'active': True,
    },
    {
        'number': 24,
        'code': 'I024',
        'label': 'Brûler un stop',
        'article': 'Art. 42',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 24,
        'active': True,
    },
    {
        'number': 25,
        'code': 'I025',
        'label': 'Franchir brusquement un carrefour',
        'article': 'Art. 140',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 25,
        'active': True,
    },
    {
        'number': 26,
        'code': 'I026',
        'label': 'Démarrer ou engager un véhicule sans inspecter la voie',
        'article': 'Art. 85',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 26,
        'active': True,
    },
    {
        'number': 27,
        'code': 'I027',
        'label': 'Faire marche arrière sur une distance supérieure à 5 m',
        'article': 'Art. 87',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 27,
        'active': True,
    },
    {
        'number': 28,
        'code': 'I028',
        'label': 'Non indication du trajet',
        'article': 'Art. 195-197',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 28,
        'active': True,
    },
    {
        'number': 29,
        'code': 'I029',
        'label': 'Dépassement dangereux',
        'article': 'Art. 80.a',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 29,
        'active': True,
    },
    {
        'number': 30,
        'code': 'I030',
        'label': 'Dépasser dans une zone interdite',
        'article': 'Art. 80.b',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 30,
        'active': True,
    },
    {
        'number': 31,
        'code': 'I031',
        'label': 'Circuler sans vignette',
        'article': 'Art. 23',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 31,
        'active': True,
    },
    {
        'number': 32,
        'code': 'I032',
        'label': 'Éblouir un autre usager',
        'article': 'Art. 49',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 32,
        'active': True,
    },
    {
        'number': 33,
        'code': 'I033',
        'label': 'Circuler sans rétroviseur',
        'article': 'Art. 151-197',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 33,
        'active': True,
    },
    {
        'number': 34,
        'code': 'I034',
        'label': "Conduire en état d'ébriété",
        'article': 'Art. 44',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 34,
        'active': True,
    },
    {
        'number': 35,
        'code': 'I035',
        'label': 'Utiliser son avertisseur sans raison valable',
        'article': 'Art. 152-162',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 35,
        'active': True,
    },
    {
        'number': 36,
        'code': 'I036',
        'label': "Ne pas s'arrêter suite à une injonction d'un agent",
        'article': 'Art. 43',
        'amount': '250',
        'penalty_text': '250',
        'category': '',
        'display_order': 36,
        'active': True,
    },
    {
        'number': 37,
        'code': 'I037',
        'label': 'Transférer ses plaques sur un autre véhicule',
        'article': 'Art. 35',
        'amount': '10000',
        'penalty_text': '10000',
        'category': '',
        'display_order': 37,
        'active': True,
    },
    {
        'number': 38,
        'code': 'I038',
        'label': 'Circuler en sens contraire',
        'article': 'Art. 78',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 38,
        'active': True,
    },
    {
        'number': 39,
        'code': 'I039',
        'label': 'Trajet non autorisé',
        'article': 'Art. 196',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 39,
        'active': True,
    },
    {
        'number': 40,
        'code': 'I040',
        'label': 'Refus de prendre un passager',
        'article': 'Art. 202.a, Art. 202.b',
        'amount': None,
        'penalty_text': '500 / 1000',
        'category': '',
        'display_order': 40,
        'active': True,
    },
    {
        'number': 41,
        'code': 'I041',
        'label': "Transporter des passagers à l'extérieur d'un véhicule / plus de passager - que le nombre autorisé(exces de chargement)",
        'article': 'Art. 205',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 41,
        'active': True,
    },
    {
        'number': 42,
        'code': 'I042',
        'label': 'Traverser ou chevaucher une bande longitudinale continue',
        'article': 'Art. 110',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 42,
        'active': True,
    },
    {
        'number': 43,
        'code': 'I043',
        'label': 'Conduire un véhicule sans avoir placé le tarif officiel et sa carte de chauffeur à la vue des passagers',
        'article': 'Art. 200',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 43,
        'active': True,
    },
    {
        'number': 44,
        'code': 'I044',
        'label': 'Conduire un véhicule public et porter des vêtements sales et indécents',
        'article': 'Art. 199',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 44,
        'active': True,
    },
    {
        'number': 45,
        'code': 'I045',
        'label': 'Traverser un cortège',
        'article': 'Art. 77',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 45,
        'active': True,
    },
    {
        'number': 46,
        'code': 'I046',
        'label': "Traverser ou dépasser une bande transversale d'arrêt lorsque le feu rouge est encore visible",
        'article': 'Art. 111',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 46,
        'active': True,
    },
    {
        'number': 47,
        'code': 'I047',
        'label': 'Circuler sur le trottoir avec un véhicule',
        'article': 'Art. 268',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 47,
        'active': True,
    },
    {
        'number': 48,
        'code': 'I048',
        'label': 'Transporter des passagers sur un véhicule non approprié',
        'article': 'Art. 201',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 48,
        'active': True,
    },
    {
        'number': 49,
        'code': 'I049',
        'label': 'Ne pas répondre à la contravention dans les 72 heures',
        'article': 'Art. 271',
        'amount': None,
        'penalty_text': '',
        'category': '',
        'display_order': 49,
        'active': True,
    },
    {
        'number': 50,
        'code': 'I050',
        'label': 'Circuler avec un véhicule dont le chargement dépasse',
        'article': 'Art. 203',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 50,
        'active': True,
    },
    {
        'number': 51,
        'code': 'I051',
        'label': 'Circuler avec des pneus usés',
        'article': 'Art. 254',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 51,
        'active': True,
    },
    {
        'number': 52,
        'code': 'I052',
        'label': 'Nuisance sonore',
        'article': 'Art. 152-162',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 52,
        'active': True,
    },
    {
        'number': 53,
        'code': 'I053',
        'label': 'Obstruction ou dégradation de la voie publique',
        'article': 'Art. 16',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 53,
        'active': True,
    },
    {
        'number': 54,
        'code': 'I054',
        'label': "Circuler sans pièces d'identification",
        'article': 'Art. 17',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 54,
        'active': True,
    },
    {
        'number': 55,
        'code': 'I055',
        'label': 'Modifier la description initiale du véhicule / le démolir sans autorisation préalable',
        'article': 'Art. 28',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 55,
        'active': True,
    },
    {
        'number': 56,
        'code': 'I056',
        'label': "Circuler sans carte d'immatriculation / carte non conforme",
        'article': 'Art. 22',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 56,
        'active': True,
    },
    {
        'number': 57,
        'code': 'I057',
        'label': 'Circuler avec plaque démonstration au-delà de 72 heures',
        'article': 'Art. 37',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 57,
        'active': True,
    },
    {
        'number': 58,
        'code': 'I058',
        'label': 'Mauvaise utilisation de plaque démonstration',
        'article': 'Art. 38',
        'amount': '250',
        'penalty_text': '250',
        'category': '',
        'display_order': 58,
        'active': True,
    },
    {
        'number': 59,
        'code': 'I059',
        'label': "Usage du téléphone cellulaire, radar, TV, radio, baladeur, lunettes bouchant l'angle de vision",
        'article': 'Art. 42',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 59,
        'active': True,
    },
    {
        'number': 60,
        'code': 'I060',
        'label': "Prêter ou donner son permis de conduire / utiliser permis d'autrui",
        'article': 'Art. 45',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 60,
        'active': True,
    },
    {
        'number': 61,
        'code': 'I061',
        'label': "Ne pas dégager la voie publique dans le délai prescrit en cas d'accident",
        'article': 'Art. 92',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 61,
        'active': True,
    },
    {
        'number': 62,
        'code': 'I062',
        'label': 'Véhicule en panne non balisé / abandonné sur voie publique',
        'article': 'Art. 93',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 62,
        'active': True,
    },
    {
        'number': 63,
        'code': 'I063',
        'label': 'Circuler dans une zone interdite / réservée aux piétons',
        'article': 'Art. 94',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 63,
        'active': True,
    },
    {
        'number': 64,
        'code': 'I064',
        'label': 'Causer un accident en franchissant un feu rouge',
        'article': 'Art. 104',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 64,
        'active': True,
    },
    {
        'number': 65,
        'code': 'I065',
        'label': 'Ne pas ralentir au feu jaune',
        'article': 'Art. 106',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 65,
        'active': True,
    },
    {
        'number': 66,
        'code': 'I066',
        'label': "Franchir une bande transversale d'arrêt au feu jaune",
        'article': 'Art. 111',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 66,
        'active': True,
    },
    {
        'number': 67,
        'code': 'I067',
        'label': "Ne pas maintenir le moteur en marche à l'arrêt au feu rouge",
        'article': 'Art. 115',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 67,
        'active': True,
    },
    {
        'number': 68,
        'code': 'I068',
        'label': 'Enlever / détériorer des panneaux de signalisation(Poursuites pénale et cout de remplacement)',
        'article': 'Art. 138',
        'amount': None,
        'penalty_text': '',
        'category': '',
        'display_order': 68,
        'active': True,
    },
    {
        'number': 69,
        'code': 'I069',
        'label': 'Afficher, inscrire ou graffiter sur les panneaux',
        'article': 'Art. 121',
        'amount': '500',
        'penalty_text': '500',
        'category': '',
        'display_order': 69,
        'active': True,
    },
    {
        'number': 70,
        'code': 'I070',
        'label': "Enlever ou détériorer une fiche d'inspection",
        'article': 'Art. 129',
        'amount': '5000',
        'penalty_text': '5000',
        'category': '',
        'display_order': 70,
        'active': True,
    },
    {
        'number': 71,
        'code': 'I071',
        'label': 'Circuler avec un véhicule déclaré hors de service',
        'article': 'Art. 151',
        'amount': None,
        'penalty_text': '500 + frais de remorquage',
        'category': '',
        'display_order': 71,
        'active': True,
    },
    {
        'number': 72,
        'code': 'I072',
        'label': 'Ne pas récupérer le véhicule remorqué dans le délai de 5 jours(vente à la criée publique)',
        'article': 'Art. 150',
        'amount': None,
        'penalty_text': '',
        'category': '',
        'display_order': 72,
        'active': True,
    },
    {
        'number': 73,
        'code': 'I073',
        'label': 'Non-respect des règles de priorité',
        'article': 'Art. 140',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 73,
        'active': True,
    },
    {
        'number': 74,
        'code': 'I074',
        'label': 'Vitres teintées, film auto-collant sur vitres et pare-brises',
        'article': 'Art. 150/162',
        'amount': '1000',
        'penalty_text': '1000',
        'category': '',
        'display_order': 74,
        'active': True,
    },
]
