# Generated by Django 5.2.14 on 2026-07-24 18:55

import apps.delits.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0007_alter_alert_options_alert_document_expires_on_and_more'),
        ('drivers', '0005_alter_driver_created_at_alter_driver_sex_and_more'),
        ('infractions', '0003_alter_infraction_options_infraction_amount_options_and_more'),
        ('scans', '0005_private_scan_storage'),
        ('tickets', '0009_alter_ticket_client_uuid_alter_ticket_created_at_and_more'),
        ('vehicles', '0004_alter_vehicle_options_alter_vehicle_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('legal_basis', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DelitCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('source_type', models.CharField(choices=[('MANUAL_OBSERVATION', 'Observation directe'), ('PLATE_SCAN', 'Scan ou recherche de plaque'), ('DRIVER_SEARCH', 'Recherche conducteur'), ('LICENSE_SEARCH', 'Recherche permis'), ('VEHICLE_CONTROL', 'Contrôle véhicule'), ('TICKET', 'Procès-verbal'), ('VERBALIZATION', 'Verbalisation'), ('ALERT', 'Alerte')], db_index=True, max_length=30)),
                ('facts', models.TextField()),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('qualification_status', models.CharField(choices=[('POTENTIAL', 'Potentiel'), ('UNDER_REVIEW', 'En révision'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté')], db_index=True, default='POTENTIAL', max_length=20)),
                ('procedure_status', models.CharField(choices=[('OPEN', 'Ouvert'), ('ACTION_TAKEN', 'Mesure prise'), ('REFERRED', 'Transmis'), ('CLOSED', 'Clôturé'), ('CANCELLED', 'Annulé')], db_index=True, default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('referred_to', models.CharField(blank=True, default='', max_length=160)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('referred_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('deduplication_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='alerts.alert')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_delit_cases', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_delit_cases', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_delit_cases', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='drivers.driver')),
                ('infraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='infractions.infraction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_delit_cases', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='scans.scan')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='tickets.ticket')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='vehicles.vehicle')),
                ('verbalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_cases', to='tickets.ticketverbalization')),
                ('delit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='delits.delittype')),
            ],
            options={
                'ordering': ('-detected_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DelitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('action_type', models.CharField(choices=[('IDENTITY_CHECK', 'Contrôle d’identité'), ('LICENSE_RETAINED', 'Permis retenu'), ('DOCUMENT_SEIZED', 'Document saisi'), ('VEHICLE_IMMOBILIZED', 'Véhicule immobilisé'), ('VEHICLE_TOWED', 'Véhicule remorqué'), ('PERSON_INTERCEPTED', 'Personne interceptée'), ('PERSON_ARRESTED', 'Personne arrêtée'), ('REFERRED_TO_AUTHORITY', 'Transmis à une autorité'), ('DOCUMENT_RETURNED', 'Document restitué'), ('VEHICLE_RELEASED', 'Véhicule libéré'), ('PERSON_RELEASED', 'Personne libérée'), ('OTHER', 'Autre')], db_index=True, max_length=32)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('authority', models.CharField(blank=True, default='', max_length=160)),
                ('reference_number', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField()),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delit_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='delits.delitcase')),
            ],
            options={
                'ordering': ('performed_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DelitEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(blank=True, null=True, storage=apps.delits.models.PrivateDelitEvidenceStorage(), upload_to=apps.delits.models.delit_evidence_upload_path)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('STATEMENT', 'Déclaration'), ('OTHER', 'Autre')], max_length=12)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('alert_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_evidence', to='alerts.alertevidence')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='delits.delitcase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delit_evidence', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_evidence', to='scans.scan')),
                ('ticket_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delit_evidence', to='tickets.ticketproof')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DelitStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_qualification_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_qualification_status', models.CharField(max_length=20)),
                ('previous_procedure_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_procedure_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='delits.delitcase')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delit_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('changed_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='delitcase',
            index=models.Index(fields=['qualification_status', 'procedure_status', 'detected_at'], name='delit_case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delitcase',
            index=models.Index(fields=['driver', 'procedure_status'], name='delit_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delitcase',
            index=models.Index(fields=['vehicle', 'procedure_status'], name='delit_vehicle_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='delitcase',
            constraint=models.UniqueConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), fields=('deduplication_key',), name='unique_delit_dedup_key'),
        ),
    ]
