# Generated by Django 5.2.14 on 2026-07-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owner_person_identity'),
        ('vehicles', '0003_vehicle_registration_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ('person__last_name', 'person__first_name', 'id'), 'verbose_name': 'Propriétaire', 'verbose_name_plural': 'Propriétaires'},
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ownership_type', models.CharField(choices=[('FULL_OWNER', 'Propriétaire principal'), ('CO_OWNER', 'Copropriétaire'), ('LEGAL_CUSTODIAN', 'Détenteur légal'), ('COMPANY_VEHICLE', "Véhicule d'entreprise"), ('GOVERNMENT_VEHICLE', 'Véhicule administratif'), ('TEMPORARY_HOLDER', 'Détenteur temporaire')], default='FULL_OWNER', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('source_document_reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vehicle_ownerships', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_vehicle_ownerships', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ownerships', to='owners.owner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Propriété de véhicule',
                'verbose_name_plural': 'Propriétés de véhicules',
                'ordering': ('-is_current', '-start_date', '-id'),
                'indexes': [models.Index(fields=['vehicle', 'is_current'], name='ownership_vehicle_current_idx'), models.Index(fields=['owner', 'is_current'], name='ownership_owner_current_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('vehicle',), name='unique_current_owner_per_vehicle'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ownership_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('is_current', True)), ('is_current', False), _connector='OR'), name='current_ownership_has_no_end_date')],
            },
        ),
    ]
